"""add stock quantity to products

Revision ID: 0adff6ed9177
Revises: 121a14804c3c
Create Date: 2026-07-29 15:53:07.822115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0adff6ed9177'
down_revision = '121a14804c3c'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "stock_quantity",
                sa.Numeric(precision=12, scale=2),
                nullable=False,
                server_default="0",
            )
        )

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column(
            "stock_quantity",
            server_default=None,
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('stock_quantity')

    # ### end Alembic commands ###
