"""add auth rbac tables

Revision ID: 38596741aae4
Revises: b81f99dbc0b6
Create Date: 2026-07-27 13:05:00.828244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38596741aae4'
down_revision = 'b81f99dbc0b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('role_permissions_role_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('role_permissions_permission_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('role_permissions_permission_id_fkey'), 'permissions', ['permission_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('role_permissions_role_id_fkey'), 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###
