"""add payment fields to invoices

Revision ID: 9daff9c69d4b
Revises: 0adff6ed9177
Create Date: 2026-07-29 16:49:54.773905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9daff9c69d4b'
down_revision = '0adff6ed9177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###

    with op.batch_alter_table(
        "invoices",
        schema=None,
    ) as batch_op:

        batch_op.add_column(
            sa.Column(
                "paid_amount",
                sa.Numeric(12, 2),
                nullable=False,
                server_default="0",
            )
        )

        batch_op.add_column(
            sa.Column(
                "due_amount",
                sa.Numeric(12, 2),
                nullable=False,
                server_default="0",
            )
        )

        batch_op.add_column(
            sa.Column(
                "payment_status",
                sa.String(30),
                nullable=False,
                server_default="UNPAID",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('payment_status')
        batch_op.drop_column('due_amount')
        batch_op.drop_column('paid_amount')

    # ### end Alembic commands ###
