"""empty message

Revision ID: bba97d9af6b7
Revises: 35027eceb5c4
Create Date: 2026-07-31 14:18:22.227055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba97d9af6b7'
down_revision = '35027eceb5c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('supplier_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('supplier_type', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('billing_address_line_1', sa.String(length=255), nullable=True),
    sa.Column('billing_address_line_2', sa.String(length=255), nullable=True),
    sa.Column('billing_city', sa.String(length=100), nullable=True),
    sa.Column('billing_state', sa.String(length=100), nullable=True),
    sa.Column('billing_country', sa.String(length=100), nullable=False),
    sa.Column('billing_postal_code', sa.String(length=20), nullable=True),
    sa.Column('shipping_address_line_1', sa.String(length=255), nullable=True),
    sa.Column('shipping_address_line_2', sa.String(length=255), nullable=True),
    sa.Column('shipping_city', sa.String(length=100), nullable=True),
    sa.Column('shipping_state', sa.String(length=100), nullable=True),
    sa.Column('shipping_country', sa.String(length=100), nullable=False),
    sa.Column('shipping_postal_code', sa.String(length=20), nullable=True),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_billing_city'), ['billing_city'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_billing_state'), ['billing_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_suppliers_gst_number'), ['gst_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_suppliers_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_shipping_city'), ['shipping_city'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_shipping_state'), ['shipping_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_supplier_code'), ['supplier_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_supplier_code'))
        batch_op.drop_index(batch_op.f('ix_suppliers_shipping_state'))
        batch_op.drop_index(batch_op.f('ix_suppliers_shipping_city'))
        batch_op.drop_index(batch_op.f('ix_suppliers_phone'))
        batch_op.drop_index(batch_op.f('ix_suppliers_name'))
        batch_op.drop_index(batch_op.f('ix_suppliers_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_suppliers_is_active'))
        batch_op.drop_index(batch_op.f('ix_suppliers_gst_number'))
        batch_op.drop_index(batch_op.f('ix_suppliers_email'))
        batch_op.drop_index(batch_op.f('ix_suppliers_billing_state'))
        batch_op.drop_index(batch_op.f('ix_suppliers_billing_city'))

    op.drop_table('suppliers')
    # ### end Alembic commands ###
